server:
  port: 8811

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruiji
    username: root
    password: 1234

  redis:
    host: 192.168.233.100
    password: 123456
    port: 6379

  cache:
    type: redis
